# Generated by Django 6.0.5 on 2026-05-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
