# Generated by Django 6.0.5 on 2026-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_updates_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='fix_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='updates',
            name='update_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='updates',
            name='included_in_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='updates',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
