# Generated by Django 6.0.5 on 2026-05-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_updates_fix_link_updates_update_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
